// AUTO-GENERATED by scripts/write-sdk-version.ts — do not edit by hand.
// The exact @anthropic-ai/claude-agent-sdk version grove was built against;
// the fetcher pulls this exact native claude binary for protocol compatibility.
export const CLAUDE_SDK_VERSION = "0.3.167";
