import { readFileSync, writeFileSync } from "node:fs";

const version = JSON.parse(
  readFileSync("node_modules/@anthropic-ai/claude-agent-sdk/package.json", "utf8"),
).version as string;

writeFileSync(
  "src/agent/sdk-version.ts",
  `// AUTO-GENERATED by scripts/write-sdk-version.ts — do not edit by hand.\n` +
    `// The exact @anthropic-ai/claude-agent-sdk version grove was built against;\n` +
    `// the fetcher pulls this exact native claude binary for protocol compatibility.\n` +
    `export const CLAUDE_SDK_VERSION = ${JSON.stringify(version)};\n`,
);

console.log(`wrote CLAUDE_SDK_VERSION=${version}`);
